# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/etri/ado/gateway/openAI.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='org/etri/ado/gateway/openAI.proto',
  package='org.etri.ado.gateway',
  syntax='proto3',
  serialized_options=_b('\n\033org.etri.ado.gateway.openaiH\001'),
  serialized_pb=_b('\n!org/etri/ado/gateway/openAI.proto\x12\x14org.etri.ado.gateway\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"&\n\x08\x41gentRef\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"8\n\x06\x41gents\x12.\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x1e.org.etri.ado.gateway.AgentRef\"$\n\x0c\x43\x61pabilities\x12\x14\n\x0c\x63\x61pabilities\x18\x01 \x03(\t\"-\n\x06\x41\x63tion\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\x02\"\x1a\n\x0bObservation\x12\x0b\n\x03obs\x18\x01 \x03(\x02\x32\xfc\x01\n\x03\x41\x44O\x12N\n\x0cgetAgentById\x12\x1c.google.protobuf.StringValue\x1a\x1e.org.etri.ado.gateway.AgentRef\"\x00\x12P\n\ngetAgentOf\x12\".org.etri.ado.gateway.Capabilities\x1a\x1c.org.etri.ado.gateway.Agents\"\x00\x12S\n\x0egetObservation\x12\x1c.google.protobuf.StringValue\x1a!.org.etri.ado.gateway.Observation\"\x00\x32\xa9\x02\n\x05\x41gent\x12?\n\x05getId\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\"\x00\x12I\n\x0bisCapableOf\x12\x1c.google.protobuf.StringValue\x1a\x1a.google.protobuf.BoolValue\"\x00\x12O\n\x0fgetCapabilities\x12\x16.google.protobuf.Empty\x1a\".org.etri.ado.gateway.Capabilities\"\x00\x12\x43\n\tsetAction\x12\x1c.org.etri.ado.gateway.Action\x1a\x16.google.protobuf.Empty\"\x00\x42\x1f\n\x1borg.etri.ado.gateway.openaiH\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_AGENTREF = _descriptor.Descriptor(
  name='AgentRef',
  full_name='org.etri.ado.gateway.AgentRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='org.etri.ado.gateway.AgentRef.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='org.etri.ado.gateway.AgentRef.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=158,
)


_AGENTS = _descriptor.Descriptor(
  name='Agents',
  full_name='org.etri.ado.gateway.Agents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agents', full_name='org.etri.ado.gateway.Agents.agents', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=216,
)


_CAPABILITIES = _descriptor.Descriptor(
  name='Capabilities',
  full_name='org.etri.ado.gateway.Capabilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capabilities', full_name='org.etri.ado.gateway.Capabilities.capabilities', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=254,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='org.etri.ado.gateway.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capability', full_name='org.etri.ado.gateway.Action.capability', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='org.etri.ado.gateway.Action.actions', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=301,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='org.etri.ado.gateway.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs', full_name='org.etri.ado.gateway.Observation.obs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=329,
)

_AGENTS.fields_by_name['agents'].message_type = _AGENTREF
DESCRIPTOR.message_types_by_name['AgentRef'] = _AGENTREF
DESCRIPTOR.message_types_by_name['Agents'] = _AGENTS
DESCRIPTOR.message_types_by_name['Capabilities'] = _CAPABILITIES
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentRef = _reflection.GeneratedProtocolMessageType('AgentRef', (_message.Message,), dict(
  DESCRIPTOR = _AGENTREF,
  __module__ = 'org.etri.ado.gateway.openAI_pb2'
  # @@protoc_insertion_point(class_scope:org.etri.ado.gateway.AgentRef)
  ))
_sym_db.RegisterMessage(AgentRef)

Agents = _reflection.GeneratedProtocolMessageType('Agents', (_message.Message,), dict(
  DESCRIPTOR = _AGENTS,
  __module__ = 'org.etri.ado.gateway.openAI_pb2'
  # @@protoc_insertion_point(class_scope:org.etri.ado.gateway.Agents)
  ))
_sym_db.RegisterMessage(Agents)

Capabilities = _reflection.GeneratedProtocolMessageType('Capabilities', (_message.Message,), dict(
  DESCRIPTOR = _CAPABILITIES,
  __module__ = 'org.etri.ado.gateway.openAI_pb2'
  # @@protoc_insertion_point(class_scope:org.etri.ado.gateway.Capabilities)
  ))
_sym_db.RegisterMessage(Capabilities)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'org.etri.ado.gateway.openAI_pb2'
  # @@protoc_insertion_point(class_scope:org.etri.ado.gateway.Action)
  ))
_sym_db.RegisterMessage(Action)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVATION,
  __module__ = 'org.etri.ado.gateway.openAI_pb2'
  # @@protoc_insertion_point(class_scope:org.etri.ado.gateway.Observation)
  ))
_sym_db.RegisterMessage(Observation)


DESCRIPTOR._options = None

_ADO = _descriptor.ServiceDescriptor(
  name='ADO',
  full_name='org.etri.ado.gateway.ADO',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=332,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAgentById',
    full_name='org.etri.ado.gateway.ADO.getAgentById',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=_AGENTREF,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAgentOf',
    full_name='org.etri.ado.gateway.ADO.getAgentOf',
    index=1,
    containing_service=None,
    input_type=_CAPABILITIES,
    output_type=_AGENTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getObservation',
    full_name='org.etri.ado.gateway.ADO.getObservation',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=_OBSERVATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADO)

DESCRIPTOR.services_by_name['ADO'] = _ADO


_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='org.etri.ado.gateway.Agent',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=587,
  serialized_end=884,
  methods=[
  _descriptor.MethodDescriptor(
    name='getId',
    full_name='org.etri.ado.gateway.Agent.getId',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isCapableOf',
    full_name='org.etri.ado.gateway.Agent.isCapableOf',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getCapabilities',
    full_name='org.etri.ado.gateway.Agent.getCapabilities',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CAPABILITIES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setAction',
    full_name='org.etri.ado.gateway.Agent.setAction',
    index=3,
    containing_service=None,
    input_type=_ACTION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
