# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from org.etri.ado.gateway import openAI_pb2 as org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2


class ADOStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getAgentById = channel.unary_unary(
        '/org.etri.ado.gateway.ADO/getAgentById',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.AgentRef.FromString,
        )
    self.getAgentOf = channel.unary_unary(
        '/org.etri.ado.gateway.ADO/getAgentOf',
        request_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Capabilities.SerializeToString,
        response_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Agents.FromString,
        )
    self.getObservation = channel.unary_unary(
        '/org.etri.ado.gateway.ADO/getObservation',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Observation.FromString,
        )


class ADOServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getAgentById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAgentOf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getObservation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ADOServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getAgentById': grpc.unary_unary_rpc_method_handler(
          servicer.getAgentById,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.AgentRef.SerializeToString,
      ),
      'getAgentOf': grpc.unary_unary_rpc_method_handler(
          servicer.getAgentOf,
          request_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Capabilities.FromString,
          response_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Agents.SerializeToString,
      ),
      'getObservation': grpc.unary_unary_rpc_method_handler(
          servicer.getObservation,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Observation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.etri.ado.gateway.ADO', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getId = channel.unary_unary(
        '/org.etri.ado.gateway.Agent/getId',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
        )
    self.isCapableOf = channel.unary_unary(
        '/org.etri.ado.gateway.Agent/isCapableOf',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.getCapabilities = channel.unary_unary(
        '/org.etri.ado.gateway.Agent/getCapabilities',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Capabilities.FromString,
        )
    self.setAction = channel.unary_unary(
        '/org.etri.ado.gateway.Agent/setAction',
        request_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Action.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def isCapableOf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCapabilities(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getId': grpc.unary_unary_rpc_method_handler(
          servicer.getId,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
      ),
      'isCapableOf': grpc.unary_unary_rpc_method_handler(
          servicer.isCapableOf,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'getCapabilities': grpc.unary_unary_rpc_method_handler(
          servicer.getCapabilities,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Capabilities.SerializeToString,
      ),
      'setAction': grpc.unary_unary_rpc_method_handler(
          servicer.setAction,
          request_deserializer=org_dot_etri_dot_ado_dot_gateway_dot_openAI__pb2.Action.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.etri.ado.gateway.Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
